[package]
name = "tokenizers" 
version = "0.12.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.153"
tokenizers = {version = "0.19.1" }

[registries.crates-io]
# speed up "Updating crates.io index"
protocol = "sparse"
